[package]
name = "spot-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde_json = "1.0"
skim = "0.10.4"

spot-lib = { path = "../spot-lib" }
